name: Build Palm Controller

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: palm_controller_app
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.0'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run tests (CI-friendly)
      env:
        SKIP_INTEGRATION_TESTS: true
        SKIP_UI_TESTS: true
      run: |
        # 运行单元测试（跳过复杂的UI和集成测试）
        flutter test test/unit/ test/widget_test.dart
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: PalmController-Android-APK
        path: palm_controller_app/build/app/outputs/flutter-apk/app-release.apk

  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: PalmControllerServer
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build
    
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: PalmController-Windows-Server
        path: PalmControllerServer/publish/ 